# Generated by Django 4.2.26 on 2025-12-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guessanym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=128)),
                ('src', models.CharField(blank=True, max_length=128, verbose_name='source')),
                ('area', models.CharField(blank=True, max_length=32)),
                ('wiki', models.CharField(blank=True, max_length=128, verbose_name='info')),
                ('mode', models.CharField(blank=True, max_length=8)),
                ('depth', models.PositiveSmallIntegerField()),
                ('word', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=2048)),
                ('paragraph', models.CharField(max_length=2048)),
                ('p1', models.CharField(max_length=128)),
                ('p2', models.CharField(max_length=128)),
                ('p3', models.CharField(blank=True, max_length=128)),
                ('p4', models.CharField(blank=True, max_length=128)),
                ('p5', models.CharField(blank=True, max_length=128)),
                ('p6', models.CharField(blank=True, max_length=128)),
                ('p7', models.CharField(blank=True, max_length=128)),
                ('p8', models.CharField(blank=True, max_length=128)),
                ('p9', models.CharField(blank=True, max_length=128)),
                ('p10', models.CharField(blank=True, max_length=108)),
                ('p11', models.CharField(blank=True, max_length=128)),
                ('p12', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'depth', 'src', 'area', 'wiki', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12')},
            },
        ),
    ]
