# Generated by Django 4.2.26 on 2025-12-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_guessanym'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guessanym',
            unique_together={('name', 'depth', 'src', 'area', 'sentence', 'paragraph', 'wiki', 'word', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12')},
        ),
    ]
