# Generated by Django 4.2.26 on 2025-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_alter_guessanym_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessanym',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
